// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using psomysqlefcore;

namespace psomysqlefcore.Migrations
{
    [DbContext(typeof(PsoMapContext))]
    partial class PsoMapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("psomysqlefcore.model.FeatureType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeatureType");
                });

            modelBuilder.Entity("psomysqlefcore.model.MapFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("FeatureTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<float>("xCoord")
                        .HasColumnType("float");

                    b.Property<float>("yCoord")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FeatureTypeId");

                    b.ToTable("MapFeature");
                });

            modelBuilder.Entity("psomysqlefcore.model.MapFeature", b =>
                {
                    b.HasOne("psomysqlefcore.model.FeatureType", "FeatureType")
                        .WithMany("MapFeatures")
                        .HasForeignKey("FeatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureType");
                });

            modelBuilder.Entity("psomysqlefcore.model.FeatureType", b =>
                {
                    b.Navigation("MapFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
